"""Persistence and artifact interfaces for runtime services."""

from typing import Protocol

from agentos.domain.artifacts import Artifact, ArtifactDraft
from agentos.domain.governance import Approval, RunClaim
from agentos.domain.missions import Mission, NewEvent
from agentos.services.missions import MissionRepository


class RuntimeRepository(MissionRepository, Protocol):
    def save(
        self,
        mission: Mission,
        expected_version: int,
        events: list[NewEvent],
        *,
        claim_token: str | None = None,
        artifacts: tuple[Artifact, ...] = (),
        approval: Approval | None = None,
        decision: Approval | None = None,
    ) -> Mission: ...
    def approval(self, approval_id: str) -> Approval: ...
    def approvals(self, mission_id: str, pending_only: bool = True) -> list[Approval]: ...
    def artifact(self, artifact_id: str) -> Artifact: ...
    def artifacts(self, mission_id: str, limit: int = 100, offset: int = 0) -> list[Artifact]: ...
    def claim(self, mission_id: str) -> RunClaim | None: ...
    def acquire_claim(self, mission_id: str, expected_version: int, actor: str) -> RunClaim: ...
    def release_claim(self, claim: RunClaim) -> None: ...
    def recover_claim(
        self, mission: Mission, expected_token: str, events: list[NewEvent]
    ) -> Mission: ...


class ArtifactStorage(Protocol):
    def write(self, mission_id: str, task_id: str, draft: ArtifactDraft) -> Artifact: ...
    def read(self, artifact: Artifact) -> bytes: ...
    def remove_uncommitted(self, artifact: Artifact) -> None: ...
